### ISSUE TITLE
Falla rake db:migrate

### ISSUE THREAD

**Issue by zeitan** [betacar/socialum#1]
Cuando ejecuto rake db:migrate  se produce el siguiente error

==  DeviseCreateUsuarios: migrating ===========================================
-- create_table(:usuarios, {:id=>false})
rake aborted!
An error has occurred, this and all later migrations canceled:

undefined method `ldap_authenticatable' for #ActiveRecord::ConnectionAdapters::PostgreSQLAdapter::TableDefinition:0x00000002c60a00

Tasks: TOP => db:migrate
(See full trace by running task with --trace)

Esto sucede por que se elimino la gema  devise_ldap del sistema pero no se cambio las migraciones.

**Comment by betacar** [comment]
No ejecutes las migraciones. Carga el `schema.rb` con `rake db:schema:load`

**Comment by zeitan** [comment]
rake db:schema:load aunque crea la DB falla en generar el pkey para la entidad usuarios lo cual produce que AREL no sepa quien es la pkey. Por otro lado no se tienen las vistas ni los otros 2 esquemas que se usan (gen, spb). Mejor solución:
Acomodar los migration en el orden correcto como deberian crearse las entidades y sus estructuras, agregar un rake final que haga la creación de los otros 2 esquemas(gen, spb) y genere las vistas en el esquema socialum
